[theme]
primaryColor = "#8C1515"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F4"
textColor = "#262626"
font = "sans serif"

[server]
runOnSave = false
headless = true

[browser]
gatherUsageStats = false
